### ISSUE TITLE
Will I get swift version ?

### ISSUE THREAD

**Issue by zahedul** [spencercarli/react-native-meteor-accounts#10]
Hi, will you please add swift version example ?

**Comment by spencercarli** [comment]
Hey sorry to disappoint but that doesn't really fall within scope of this project, as this is related to React Native rather than swift/objective-c/java specifically. Here are a few resources that may help you
- [SwiftDDP](https://github.com/siegesmund/SwiftDDP)
- [meteor-ios](https://github.com/martijnwalraven/meteor-ios)
